/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VerifikasiRouteImport } from './routes/verifikasi'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated/contacts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedQueueRouteImport } from './routes/_authenticated/queue'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as ApiCampaignDispatchRouteImport } from './routes/api/campaign/dispatch'
import { Route as ApiSessionIdRouteImport } from './routes/api/session/$id'
import { Route as ApiPublicCronProcessQueueRouteImport } from './routes/api/public/cron/process-queue'
import { Route as ApiPublicDbSplatRouteImport } from './routes/api/public/db/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifikasiRoute = VerifikasiRouteImport.update({
  id: '/verifikasi',
  path: '/verifikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQueueRoute = AuthenticatedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiCampaignDispatchRoute = ApiCampaignDispatchRouteImport.update({
  id: '/api/campaign/dispatch',
  path: '/api/campaign/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionIdRoute = ApiSessionIdRouteImport.update({
  id: '/api/session/$id',
  path: '/api/session/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronProcessQueueRoute =
  ApiPublicCronProcessQueueRouteImport.update({
    id: '/api/public/cron/process-queue',
    path: '/api/public/cron/process-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDbSplatRoute = ApiPublicDbSplatRouteImport.update({
  id: '/api/public/db/$',
  path: '/api/public/db/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verifikasi': typeof VerifikasiRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/campaign/dispatch': typeof ApiCampaignDispatchRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/db/$': typeof ApiPublicDbSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/verifikasi': typeof VerifikasiRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRoute
  '/queue': typeof AuthenticatedQueueRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/api/campaign/dispatch': typeof ApiCampaignDispatchRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/db/$': typeof ApiPublicDbSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/verifikasi': typeof VerifikasiRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRoute
  '/_authenticated/queue': typeof AuthenticatedQueueRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/api/campaign/dispatch': typeof ApiCampaignDispatchRoute
  '/api/session/$id': typeof ApiSessionIdRoute
  '/api/public/cron/process-queue': typeof ApiPublicCronProcessQueueRoute
  '/api/public/db/$': typeof ApiPublicDbSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/verifikasi'
    | '/admin'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/devices'
    | '/queue'
    | '/referral'
    | '/rewards'
    | '/settings'
    | '/templates'
    | '/api/campaign/dispatch'
    | '/api/session/$id'
    | '/api/public/cron/process-queue'
    | '/api/public/db/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/verifikasi'
    | '/admin'
    | '/campaigns'
    | '/contacts'
    | '/dashboard'
    | '/devices'
    | '/queue'
    | '/referral'
    | '/rewards'
    | '/settings'
    | '/templates'
    | '/api/campaign/dispatch'
    | '/api/session/$id'
    | '/api/public/cron/process-queue'
    | '/api/public/db/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/verifikasi'
    | '/_authenticated/admin'
    | '/_authenticated/campaigns'
    | '/_authenticated/contacts'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/queue'
    | '/_authenticated/referral'
    | '/_authenticated/rewards'
    | '/_authenticated/settings'
    | '/_authenticated/templates'
    | '/api/campaign/dispatch'
    | '/api/session/$id'
    | '/api/public/cron/process-queue'
    | '/api/public/db/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifikasiRoute: typeof VerifikasiRoute
  ApiCampaignDispatchRoute: typeof ApiCampaignDispatchRoute
  ApiSessionIdRoute: typeof ApiSessionIdRoute
  ApiPublicCronProcessQueueRoute: typeof ApiPublicCronProcessQueueRoute
  ApiPublicDbSplatRoute: typeof ApiPublicDbSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifikasi': {
      id: '/verifikasi'
      path: '/verifikasi'
      fullPath: '/verifikasi'
      preLoaderRoute: typeof VerifikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/queue': {
      id: '/_authenticated/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthenticatedQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/campaign/dispatch': {
      id: '/api/campaign/dispatch'
      path: '/api/campaign/dispatch'
      fullPath: '/api/campaign/dispatch'
      preLoaderRoute: typeof ApiCampaignDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/$id': {
      id: '/api/session/$id'
      path: '/api/session/$id'
      fullPath: '/api/session/$id'
      preLoaderRoute: typeof ApiSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/process-queue': {
      id: '/api/public/cron/process-queue'
      path: '/api/public/cron/process-queue'
      fullPath: '/api/public/cron/process-queue'
      preLoaderRoute: typeof ApiPublicCronProcessQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/db/$': {
      id: '/api/public/db/$'
      path: '/api/public/db/$'
      fullPath: '/api/public/db/$'
      preLoaderRoute: typeof ApiPublicDbSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRoute
  AuthenticatedQueueRoute: typeof AuthenticatedQueueRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRoute,
  AuthenticatedQueueRoute: AuthenticatedQueueRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifikasiRoute: VerifikasiRoute,
  ApiCampaignDispatchRoute: ApiCampaignDispatchRoute,
  ApiSessionIdRoute: ApiSessionIdRoute,
  ApiPublicCronProcessQueueRoute: ApiPublicCronProcessQueueRoute,
  ApiPublicDbSplatRoute: ApiPublicDbSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
